### ISSUE TITLE
store keywords in model object

### ISSUE THREAD

**Issue by msaeltzer** [koheiw/seededlda#18]
Hey Kohei, Great package! I think it would make sense to automatically store seed terms in the model object for later replication and validation. I just built an oolong plugin for word intrusion tests. Right now users have to integrate their dictionaries themselves. 
Best regards

**Comment by koheiw** [comment]
@msaeltzer can you check if #20 adds what you need.

**Comment by koheiw** [comment]
@msaeltzer does your :+1: mean that the PR is satisfies your need?

**Comment by msaeltzer** [comment]
based on the code it looks like everything is there! I will check in a couple of days when I rerun the next models.
