### ISSUE TITLE
strange error with lda & seededlda

### ISSUE THREAD

**Issue by acero83** [koheiw/seededlda#21]
the first time that I tried lda & seededlda on RStudio, they worked... however, I ran them again and suddenly they were no longer working generating the errors attached (concerning "terms" and "topics"). 

I tried with base R and got the same output: the first time it was working, since the second attempt they failed

instead, "predict" is always perfectly working.

I ran the examples on the vignette and all the required packages are installed and updated, I'm working on windows just in case.

any guess about the source of this problem and possible solutions? thanks!

![error](https://user-images.githubusercontent.com/85893523/121924102-e2fe1900-cd3b-11eb-887c-a6e0852886bb.png)

**Comment by koheiw** [comment]
I suspect that other package's `terms()` is called. Try `seededlda::terms(lda)` or `require(seededlda)` after other packages.

**Comment by acero83** [comment]
> I suspect that other package's `terms()` is called. Try `seededlda::terms(lda)` or `require(seededlda)` after other packages.

thanks for the super prompt answer.. yes, with `seededlda::XXXX` it works
