### ISSUE TITLE
Probabilities for topics

### ISSUE THREAD

**Issue by sonamgupta1105** [koheiw/seededlda#22]
I am using seededLDA and I am trying to obtain probabilities like how we can get the gamma values from traditional LDA. Is there any way to do the same for seededLDA package or some workaround maybe? @koheiw 
I am trying to use the topic model results and fit a logistic regression model.

**Comment by koheiw** [comment]
For both seeded LDA and regular LDA, theta is the probabilities of documents for topics., so you only just to access `lda$theta` where `lad` is the fitted model.
