### ISSUE TITLE
Comparing with topicmodels::LDA

### ISSUE THREAD

**Issue by masa126** [koheiw/seededlda#28]
Dear Kohei,
I guess the theta matrix of your seededlda::textmodel_lda is same as the gamma matrix of textmodels:LDA.
I set the proc parameters such as Gibbs sampling, random seed are same for both.
I found significant difference between  the per-document-per-topic-probability values.
I applied 110 sections of "Kokoro" written by Soseki Natsume as the test data. 
[kokoro_df2-m50-71z.csv](https://github.com/koheiw/seededlda/files/8309366/kokoro_df2-m50-71z.csv)

Please find a sample comparing result  as an attached png.
![kokoro_df2-LDA-slda_2k-10tpc-gamma-T28](https://user-images.githubusercontent.com/50834087/159124013-a8ec3538-277f-4985-b87e-b31c15619822.png)

Will you kindly show me the detail calculation of theta matrix?

Masataka

**Comment by koheiw** [comment]
It is an interesting experiment. Can you upload the code and the data for me to investigate?

**Comment by masa126** [comment]
Sorry to late my response.
Please find the input data (DTM) and my R scripts in the below.
[Kokoro-LDA-TopicRatio.txt](https://github.com/koheiw/seededlda/files/8324378/Kokoro-LDA-TopicRatio.txt)
[kokoro_71w_DTM.csv](https://github.com/koheiw/seededlda/files/8324379/kokoro_71w_DTM.csv)
Regards

**Comment by koheiw** [comment]
We need to modify C++ code in creating R packages. seededlda and topicmodels use different mechanism for random number generation, for example. I also rewrote the code from GibbsLDA++ entirely to replace arrays with vectors.

You might understand the difference if you compare these two files:

https://github.com/koheiw/seededlda/blob/master/src/lda.h
https://github.com/cran/topicmodels/blob/master/src/model.h

**Comment by masa126** [comment]
Thank you for your comments. 
I understand the difference between topicmodels and seededlda is caused by the mechanism for random number generation.
