### ISSUE TITLE
Compute likelihood of fitted models

### ISSUE THREAD

**Issue by masa126** [koheiw/seededlda#31]
Hi,
I want to confirm the difference between topicmodels and your seededlda.
To evaluate the LDA text-model quality, topicmodels stores loglikliehood and logLiks during the Gibbs sampling.
But I can't find these parameters in seededlda results.
Will you kindly suggest me to get these parameters?

**Comment by koheiw** [comment]
seededlda is based on [GibbsLDA](https://github.com/koheiw/GibbsLDA), so there is no likelihood statistic at the moment. I am planing to add this in the upcoming versions.
