### ISSUE TITLE
Setting options(seededlda_threads = 1) gives reproducible results, otherwise not.

### ISSUE THREAD

**Issue by myliserta** [koheiw/seededlda#76]
The documentation needs to clarify how to set a seed for each sub-processes when multi-threading.

Reference for this problem: https://stackoverflow.com/questions/78248050/set-seed-in-quantedas-lda-function

**Comment by koheiw** [comment]
I updated MAN recently. Is this enough?

https://github.com/koheiw/seededlda/blob/004af95da0ad325e74a373270fe9c74269191976/R/lda.R#L36-L40

**Comment by myliserta** [comment]
This should be enough, thank you. Alternatively, would it be possible to have a set.seed() work in parallel algorithms, or is it too dependent on the Operating System?

**Comment by koheiw** [comment]
I don't think I can. If I fix the order of parallel processioning, its performance gain will disappear.
